/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blacktshirtdev;

import java.awt.Button;
import java.awt.Label;

/**
 *
 * @author logan
 */
public class EntryGUI2 extends javax.swing.JFrame {

    /**
     * Creates new form EntryGUI2
     */
    public EntryGUI2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        startPanel = new javax.swing.JPanel();
        singlePlayerButton = new javax.swing.JButton();
        twoPlayerButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        leaderBoardTextArea = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        chaosModeButton = new javax.swing.JToggleButton();
        startSettingsButt = new javax.swing.JToggleButton();
        firstplayersettingsPanel = new javax.swing.JPanel();
        difficultySlider = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        buttonGoBack = new javax.swing.JButton();
        buttonStartOptions = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        nameSettingLabel = new javax.swing.JLabel();
        gradeSettingLabel = new javax.swing.JLabel();
        teacherSettingLabel = new javax.swing.JLabel();
        firstplayerPanel = new javax.swing.JPanel();
        AddButt = new javax.swing.JToggleButton();
        SubButt = new javax.swing.JToggleButton();
        DivButt = new javax.swing.JToggleButton();
        MultiButt = new javax.swing.JToggleButton();
        NumButt1 = new javax.swing.JToggleButton();
        NumButt3 = new javax.swing.JToggleButton();
        NumButt2 = new javax.swing.JToggleButton();
        NumButt4 = new javax.swing.JToggleButton();
        firstNumLabel = new javax.swing.JLabel();
        secondNumLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        hintButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        shuffleButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        quitButton = new javax.swing.JButton();
        pointsAmountLabel = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        highScoreAmount = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        youwinPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        buttQuit = new javax.swing.JButton();
        buttPlayAgain = new javax.swing.JButton();
        explanationPanel = new javax.swing.JPanel();
        twoPlayerPanel = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        AddButt1 = new javax.swing.JToggleButton();
        SubButt1 = new javax.swing.JToggleButton();
        DivButt1 = new javax.swing.JToggleButton();
        MultiButt1 = new javax.swing.JToggleButton();
        NumButt5 = new javax.swing.JToggleButton();
        NumButt6 = new javax.swing.JToggleButton();
        NumButt7 = new javax.swing.JToggleButton();
        NumButt8 = new javax.swing.JToggleButton();
        firstNumLabel1 = new javax.swing.JLabel();
        secondNumLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        hintButton1 = new javax.swing.JButton();
        resetButton1 = new javax.swing.JButton();
        shuffleButton1 = new javax.swing.JButton();
        helpButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        logTextArea1 = new javax.swing.JTextArea();
        quitButton1 = new javax.swing.JButton();
        pointsAmountLabel1 = new javax.swing.JLabel();
        twoplayerComporCoOp = new javax.swing.JPanel();
        compStartButton = new javax.swing.JToggleButton();
        coopStartButton = new javax.swing.JToggleButton();
        twoPlayerSettingPanel = new javax.swing.JPanel();
        beServerRadioButton = new javax.swing.JRadioButton();
        connectToRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        serverPortTextField = new javax.swing.JTextField();
        clientAddressTextField = new javax.swing.JTextField();
        connectToPortTextField = new javax.swing.JTextField();
        twoPlayerQuitButt = new javax.swing.JToggleButton();
        startTwoPlayerButt = new javax.swing.JToggleButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        serverToConnectLabel = new javax.swing.JLabel();
        addressToConnectToLabel = new javax.swing.JLabel();
        firstTimeUsePanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        gradeTextField = new javax.swing.JTextField();
        teacherNameTextField = new javax.swing.JTextField();
        firstUseQuitButton = new javax.swing.JToggleButton();
        startContinueButton = new javax.swing.JToggleButton();
        startSettingsPanel = new javax.swing.JPanel();
        youLosePanel = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        youLoseQuitButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game of 24");

        mainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPanel.setLayout(new java.awt.CardLayout());

        singlePlayerButton.setText("Single Player");
        singlePlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singlePlayerButtonActionPerformed(evt);
            }
        });

        twoPlayerButton.setText("Two Player");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Leader Board");

        leaderBoardTextArea.setColumns(20);
        leaderBoardTextArea.setRows(5);
        jScrollPane3.setViewportView(leaderBoardTextArea);

        jLabel17.setFont(new java.awt.Font("Alien Encounters", 0, 48)); // NOI18N
        jLabel17.setText("Go For 24");

        chaosModeButton.setText("Chaos Mode");

        startSettingsButt.setText("Settings");

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7))
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(twoPlayerButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(singlePlayerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chaosModeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(startSettingsButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 264, Short.MAX_VALUE))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addContainerGap(135, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel17)))
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(singlePlayerButton)
                        .addGap(14, 14, 14)
                        .addComponent(twoPlayerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chaosModeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(startSettingsButt)
                        .addGap(43, 43, 43))))
        );

        mainPanel.add(startPanel, "panelStartMenu");

        difficultySlider.setMajorTickSpacing(10);
        difficultySlider.setPaintTicks(true);
        difficultySlider.setSnapToTicks(true);
        difficultySlider.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("Difficulty");

        jLabel9.setText("Medium");

        jLabel10.setText("Hard");

        jLabel11.setText("Easy");

        buttonGoBack.setText("Go Back");

        buttonStartOptions.setText("Start");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Student Information");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("the harder it is the less solutions to the numbers choosen");

        jLabel29.setText("Name:");

        jLabel30.setText("Grade:");

        jLabel31.setText("Teacher:");

        nameSettingLabel.setText("jLabel32");

        gradeSettingLabel.setText("jLabel32");

        teacherSettingLabel.setText("jLabel32");

        javax.swing.GroupLayout firstplayersettingsPanelLayout = new javax.swing.GroupLayout(firstplayersettingsPanel);
        firstplayersettingsPanel.setLayout(firstplayersettingsPanelLayout);
        firstplayersettingsPanelLayout.setHorizontalGroup(
            firstplayersettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstplayersettingsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(firstplayersettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstplayersettingsPanelLayout.createSequentialGroup()
                        .addGroup(firstplayersettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(firstplayersettingsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138)
                                .addComponent(jLabel9))
                            .addGroup(firstplayersettingsPanelLayout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addComponent(buttonGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(firstplayersettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(firstplayersettingsPanelLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(buttonStartOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(firstplayersettingsPanelLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstplayersettingsPanelLayout.createSequentialGroup()
                        .addGroup(firstplayersettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(difficultySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(firstplayersettingsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel28)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                        .addGroup(firstplayersettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(firstplayersettingsPanelLayout.createSequentialGroup()
                                .addGroup(firstplayersettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(firstplayersettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teacherSettingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gradeSettingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameSettingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(64, 64, 64))))
        );
        firstplayersettingsPanelLayout.setVerticalGroup(
            firstplayersettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstplayersettingsPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel12)
                .addGap(42, 42, 42)
                .addGroup(firstplayersettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(nameSettingLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(firstplayersettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstplayersettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28))
                    .addGroup(firstplayersettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(gradeSettingLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstplayersettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(teacherSettingLabel))
                .addGap(29, 29, 29)
                .addComponent(difficultySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(firstplayersettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(79, 79, 79)
                .addGroup(firstplayersettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonGoBack)
                    .addComponent(buttonStartOptions))
                .addContainerGap())
        );

        mainPanel.add(firstplayersettingsPanel, "panelSinglePlayerOptions");

        firstplayerPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        AddButt.setLabel("+");
        AddButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtActionPerformed(evt);
            }
        });

        SubButt.setLabel("-");

        DivButt.setLabel("/");

        MultiButt.setLabel("*");

        NumButt1.setText("jToggleButton5");
        NumButt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumButt1ActionPerformed(evt);
            }
        });

        NumButt3.setText("jToggleButton6");

        NumButt2.setText("jToggleButton7");

        NumButt4.setText("jToggleButton8");

        firstNumLabel.setText("jLabel1");

        secondNumLabel.setText("jLabel3");

        jLabel3.setText("Number 1");

        jLabel4.setText("Number 2");

        jLabel6.setText("Points:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Math Log");

        hintButton.setText("Hint");

        resetButton.setText("Reset");

        shuffleButton.setText("Shuffle");

        helpButton.setText("Help");

        logTextArea.setColumns(20);
        logTextArea.setRows(5);
        jScrollPane1.setViewportView(logTextArea);

        quitButton.setText("Quit");

        pointsAmountLabel.setText(" ");

        jLabel27.setText("High Score:");
        jLabel27.setToolTipText("");

        highScoreAmount.setText("0");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel33.setText("How to Play:");

        jLabel34.setText("1: Select your first number");

        jLabel35.setText("2: Select your second number");

        jLabel36.setText("3: Select what mathematical operation you want to perform");

        jLabel37.setText("4: Make one button have '24' and all the others '0'");

        jLabel38.setText("5: Win!");

        javax.swing.GroupLayout firstplayerPanelLayout = new javax.swing.GroupLayout(firstplayerPanel);
        firstplayerPanel.setLayout(firstplayerPanelLayout);
        firstplayerPanelLayout.setHorizontalGroup(
            firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstplayerPanelLayout.createSequentialGroup()
                .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(firstplayerPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(firstplayerPanelLayout.createSequentialGroup()
                                .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, firstplayerPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(firstplayerPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(firstNumLabel))
                                        .addGap(56, 56, 56)
                                        .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(AddButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(DivButt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(MultiButt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(SubButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(38, 38, 38)
                                        .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(secondNumLabel)
                                            .addComponent(jLabel4))
                                        .addGap(31, 31, 31))
                                    .addGroup(firstplayerPanelLayout.createSequentialGroup()
                                        .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(hintButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(shuffleButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(resetButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(helpButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
                                        .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NumButt1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NumButt3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(67, 67, 67)
                                        .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NumButt4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NumButt2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(67, 67, 67))
                            .addGroup(firstplayerPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(firstplayerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pointsAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(firstplayerPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(highScoreAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)))
                .addContainerGap())
        );
        firstplayerPanelLayout.setVerticalGroup(
            firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstplayerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pointsAmountLabel)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(highScoreAmount)
                    .addComponent(jLabel35))
                .addGap(7, 7, 7)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(firstplayerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel38)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstplayerPanelLayout.createSequentialGroup()
                        .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(firstplayerPanelLayout.createSequentialGroup()
                                .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NumButt1)
                                    .addComponent(NumButt2))
                                .addGap(43, 43, 43)
                                .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NumButt3)
                                    .addComponent(NumButt4))
                                .addGap(31, 31, 31)
                                .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstplayerPanelLayout.createSequentialGroup()
                                        .addComponent(secondNumLabel)
                                        .addGap(67, 67, 67))
                                    .addGroup(firstplayerPanelLayout.createSequentialGroup()
                                        .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstplayerPanelLayout.createSequentialGroup()
                                                .addGroup(firstplayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(AddButt)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel3))
                                                .addGap(33, 33, 33)
                                                .addComponent(firstNumLabel)
                                                .addGap(35, 35, 35))
                                            .addGroup(firstplayerPanelLayout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(SubButt)
                                                .addGap(15, 15, 15)
                                                .addComponent(DivButt)))
                                        .addComponent(MultiButt))))
                            .addGroup(firstplayerPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(hintButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resetButton)
                                .addGap(12, 12, 12)
                                .addComponent(shuffleButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(helpButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(quitButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(firstplayerPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        AddButt.getAccessibleContext().setAccessibleName("AddButton");
        SubButt.getAccessibleContext().setAccessibleName("SubButton");
        DivButt.getAccessibleContext().setAccessibleName("DivButton");
        MultiButt.getAccessibleContext().setAccessibleName("MultiButton");
        NumButt1.getAccessibleContext().setAccessibleName("NumButt1");
        NumButt3.getAccessibleContext().setAccessibleName("NumButt3");
        NumButt2.getAccessibleContext().setAccessibleName("NumButt2");
        NumButt4.getAccessibleContext().setAccessibleName("NumButt4");
        firstNumLabel.getAccessibleContext().setAccessibleName("firstNumLabel");
        secondNumLabel.getAccessibleContext().setAccessibleName("secondNumLabel");

        mainPanel.add(firstplayerPanel, "panelSinglePlayer");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel13.setText("You made 24!");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel14.setText("You Win!");

        buttQuit.setText("Quit");

        buttPlayAgain.setText("Play Again");

        javax.swing.GroupLayout youwinPanelLayout = new javax.swing.GroupLayout(youwinPanel);
        youwinPanel.setLayout(youwinPanelLayout);
        youwinPanelLayout.setHorizontalGroup(
            youwinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(youwinPanelLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(buttQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addComponent(buttPlayAgain)
                .addGap(0, 431, Short.MAX_VALUE))
            .addGroup(youwinPanelLayout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addGroup(youwinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(youwinPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        youwinPanelLayout.setVerticalGroup(
            youwinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(youwinPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel14)
                .addGap(79, 79, 79)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addGroup(youwinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttQuit)
                    .addComponent(buttPlayAgain))
                .addContainerGap())
        );

        mainPanel.add(youwinPanel, "panelWinning");

        javax.swing.GroupLayout explanationPanelLayout = new javax.swing.GroupLayout(explanationPanel);
        explanationPanel.setLayout(explanationPanelLayout);
        explanationPanelLayout.setHorizontalGroup(
            explanationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 943, Short.MAX_VALUE)
        );
        explanationPanelLayout.setVerticalGroup(
            explanationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        mainPanel.add(explanationPanel, "panelExplain");

        twoPlayerPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label2.setName("label1"); // NOI18N
        label2.setText("Click on 2 numbers and then an Operator");

        AddButt1.setLabel("+");
        AddButt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButt1ActionPerformed(evt);
            }
        });

        SubButt1.setLabel("-");

        DivButt1.setLabel("/");

        MultiButt1.setLabel("*");

        NumButt5.setText("jToggleButton5");
        NumButt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumButt5ActionPerformed(evt);
            }
        });

        NumButt6.setText("jToggleButton6");

        NumButt7.setText("jToggleButton7");

        NumButt8.setText("jToggleButton8");

        firstNumLabel1.setText("jLabel1");

        secondNumLabel1.setText("jLabel3");

        jLabel5.setText("Number 1");

        jLabel15.setText("Number 2");

        jLabel16.setText("Points:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Math Log");

        hintButton1.setText("Hint");

        resetButton1.setText("Reset");

        shuffleButton1.setText("Shuffle");

        helpButton1.setText("Help");

        logTextArea1.setColumns(20);
        logTextArea1.setRows(5);
        jScrollPane2.setViewportView(logTextArea1);

        quitButton1.setText("Quit");

        pointsAmountLabel1.setText(" ");

        javax.swing.GroupLayout twoPlayerPanelLayout = new javax.swing.GroupLayout(twoPlayerPanel);
        twoPlayerPanel.setLayout(twoPlayerPanelLayout);
        twoPlayerPanelLayout.setHorizontalGroup(
            twoPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(twoPlayerPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(twoPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, twoPlayerPanelLayout.createSequentialGroup()
                        .addGroup(twoPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hintButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(shuffleButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resetButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(helpButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                        .addGroup(twoPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(firstNumLabel1))
                        .addGap(54, 54, 54)
                        .addGroup(twoPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(twoPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SubButt1)
                                .addComponent(AddButt1)
                                .addComponent(DivButt1))
                            .addGroup(twoPlayerPanelLayout.createSequentialGroup()
                                .addComponent(MultiButt1)
                                .addGap(4, 4, 4)))
                        .addGap(38, 38, 38)
                        .addGroup(twoPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secondNumLabel1)
                            .addComponent(jLabel15))
                        .addGap(31, 31, 31))
                    .addGroup(twoPlayerPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(twoPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(twoPlayerPanelLayout.createSequentialGroup()
                                .addGroup(twoPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumButt5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NumButt6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67)
                                .addGroup(twoPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumButt8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NumButt7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(67, 67, 67)
                .addGroup(twoPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(twoPlayerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pointsAmountLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        twoPlayerPanelLayout.setVerticalGroup(
            twoPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, twoPlayerPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(twoPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(pointsAmountLabel1))
                .addGap(31, 31, 31)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(twoPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(twoPlayerPanelLayout.createSequentialGroup()
                        .addGroup(twoPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumButt5)
                            .addComponent(NumButt7))
                        .addGap(43, 43, 43)
                        .addGroup(twoPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumButt6)
                            .addComponent(NumButt8))
                        .addGroup(twoPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(twoPlayerPanelLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(SubButt1)
                                .addGap(15, 15, 15)
                                .addComponent(DivButt1)
                                .addGap(18, 18, 18)
                                .addComponent(MultiButt1))
                            .addGroup(twoPlayerPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(twoPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, twoPlayerPanelLayout.createSequentialGroup()
                                        .addGroup(twoPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(twoPlayerPanelLayout.createSequentialGroup()
                                                .addComponent(hintButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(resetButton1)
                                                .addGap(12, 12, 12))
                                            .addGroup(twoPlayerPanelLayout.createSequentialGroup()
                                                .addGroup(twoPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(AddButt1)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jLabel5))
                                                .addGap(29, 29, 29)))
                                        .addGroup(twoPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(shuffleButton1)
                                            .addComponent(firstNumLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(helpButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(quitButton1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, twoPlayerPanelLayout.createSequentialGroup()
                                        .addComponent(secondNumLabel1)
                                        .addGap(75, 75, 75)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPanel.add(twoPlayerPanel, "panelTwoPlayer");

        compStartButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        compStartButton.setText("Play Competitive With a Friend");

        coopStartButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        coopStartButton.setText("Play Co Op With a Friend");

        javax.swing.GroupLayout twoplayerComporCoOpLayout = new javax.swing.GroupLayout(twoplayerComporCoOp);
        twoplayerComporCoOp.setLayout(twoplayerComporCoOpLayout);
        twoplayerComporCoOpLayout.setHorizontalGroup(
            twoplayerComporCoOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(twoplayerComporCoOpLayout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(compStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(coopStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        twoplayerComporCoOpLayout.setVerticalGroup(
            twoplayerComporCoOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, twoplayerComporCoOpLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(twoplayerComporCoOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coopStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(205, 205, 205))
        );

        mainPanel.add(twoplayerComporCoOp, "panelTwoPlayerCoopofComp");

        beServerRadioButton.setText("jRadioButton1");

        connectToRadioButton.setText("jRadioButton2");

        jLabel2.setText("Make a game for friends to connect to");

        jLabel18.setText("Connect to friends game");

        clientAddressTextField.setText("localhost");

        twoPlayerQuitButt.setText("Quit");

        startTwoPlayerButt.setText("Start");

        jLabel25.setText("Address");

        jLabel26.setText("Port");

        addressToConnectToLabel.setText("jLabel28");

        javax.swing.GroupLayout twoPlayerSettingPanelLayout = new javax.swing.GroupLayout(twoPlayerSettingPanel);
        twoPlayerSettingPanel.setLayout(twoPlayerSettingPanelLayout);
        twoPlayerSettingPanelLayout.setHorizontalGroup(
            twoPlayerSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(twoPlayerSettingPanelLayout.createSequentialGroup()
                .addGroup(twoPlayerSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, twoPlayerSettingPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(twoPlayerQuitButt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(twoPlayerSettingPanelLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(twoPlayerSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(serverToConnectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(twoPlayerSettingPanelLayout.createSequentialGroup()
                                .addGroup(twoPlayerSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(beServerRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(connectToRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGap(59, 59, 59)
                                .addGroup(twoPlayerSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(addressToConnectToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)))
                .addGroup(twoPlayerSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startTwoPlayerButt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(twoPlayerSettingPanelLayout.createSequentialGroup()
                        .addGroup(twoPlayerSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientAddressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                        .addGroup(twoPlayerSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(twoPlayerSettingPanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(twoPlayerSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(connectToPortTextField)
                                    .addComponent(serverPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, twoPlayerSettingPanelLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        twoPlayerSettingPanelLayout.setVerticalGroup(
            twoPlayerSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(twoPlayerSettingPanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(twoPlayerSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(26, 26, 26)
                .addGroup(twoPlayerSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beServerRadioButton)
                    .addComponent(jLabel2)
                    .addComponent(serverPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(twoPlayerSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connectToRadioButton)
                    .addComponent(jLabel18)
                    .addComponent(clientAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connectToPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(serverToConnectLabel)
                .addGap(28, 28, 28)
                .addComponent(addressToConnectToLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(twoPlayerSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twoPlayerQuitButt)
                    .addComponent(startTwoPlayerButt))
                .addGap(28, 28, 28))
        );

        mainPanel.add(twoPlayerSettingPanel, "panelTwoPlayerOption");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel20.setText("Welcome to Go For 24!");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("It seems this is your first time playing. Please enter your details below so we can get started!");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Your Name");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Grade");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Teacher's Name");

        firstUseQuitButton.setText("Quit");

        startContinueButton.setText("Continue");

        javax.swing.GroupLayout firstTimeUsePanelLayout = new javax.swing.GroupLayout(firstTimeUsePanel);
        firstTimeUsePanel.setLayout(firstTimeUsePanelLayout);
        firstTimeUsePanelLayout.setHorizontalGroup(
            firstTimeUsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstTimeUsePanelLayout.createSequentialGroup()
                .addGroup(firstTimeUsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstTimeUsePanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(firstTimeUsePanelLayout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel20))
                    .addGroup(firstTimeUsePanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(firstTimeUsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(35, 35, 35)
                        .addGroup(firstTimeUsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTextField)
                            .addComponent(gradeTextField)
                            .addComponent(teacherNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                    .addGroup(firstTimeUsePanelLayout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(firstUseQuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(startContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        firstTimeUsePanelLayout.setVerticalGroup(
            firstTimeUsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstTimeUsePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel21)
                .addGap(66, 66, 66)
                .addGroup(firstTimeUsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(firstTimeUsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(gradeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(firstTimeUsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(teacherNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(firstTimeUsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstUseQuitButton)
                    .addComponent(startContinueButton))
                .addContainerGap())
        );

        mainPanel.add(firstTimeUsePanel, "firstTimeUsePanel");

        javax.swing.GroupLayout startSettingsPanelLayout = new javax.swing.GroupLayout(startSettingsPanel);
        startSettingsPanel.setLayout(startSettingsPanelLayout);
        startSettingsPanelLayout.setHorizontalGroup(
            startSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 943, Short.MAX_VALUE)
        );
        startSettingsPanelLayout.setVerticalGroup(
            startSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        mainPanel.add(startSettingsPanel, "panelStartSettings");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel32.setText("You Lose");

        youLoseQuitButton.setText("Quit");

        javax.swing.GroupLayout youLosePanelLayout = new javax.swing.GroupLayout(youLosePanel);
        youLosePanel.setLayout(youLosePanelLayout);
        youLosePanelLayout.setHorizontalGroup(
            youLosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(youLosePanelLayout.createSequentialGroup()
                .addContainerGap(383, Short.MAX_VALUE)
                .addGroup(youLosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, youLosePanelLayout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(349, 349, 349))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, youLosePanelLayout.createSequentialGroup()
                        .addComponent(youLoseQuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(409, 409, 409))))
        );
        youLosePanelLayout.setVerticalGroup(
            youLosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(youLosePanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(youLoseQuitButton)
                .addGap(104, 104, 104))
        );

        mainPanel.add(youLosePanel, "panelYouLose");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void singlePlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singlePlayerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_singlePlayerButtonActionPerformed

    private void NumButt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumButt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumButt1ActionPerformed

    private void AddButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddButtActionPerformed

    private void AddButt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddButt1ActionPerformed

    private void NumButt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumButt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumButt5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntryGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntryGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntryGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntryGUI2().setVisible(true);
            }
        });
        
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToggleButton AddButt;
    public javax.swing.JToggleButton AddButt1;
    public javax.swing.JToggleButton DivButt;
    public javax.swing.JToggleButton DivButt1;
    public javax.swing.JToggleButton MultiButt;
    public javax.swing.JToggleButton MultiButt1;
    public javax.swing.JToggleButton NumButt1;
    public javax.swing.JToggleButton NumButt2;
    public javax.swing.JToggleButton NumButt3;
    public javax.swing.JToggleButton NumButt4;
    public javax.swing.JToggleButton NumButt5;
    public javax.swing.JToggleButton NumButt6;
    public javax.swing.JToggleButton NumButt7;
    public javax.swing.JToggleButton NumButt8;
    public javax.swing.JToggleButton SubButt;
    public javax.swing.JToggleButton SubButt1;
    public javax.swing.JLabel addressToConnectToLabel;
    public javax.swing.JRadioButton beServerRadioButton;
    public javax.swing.JButton buttPlayAgain;
    public javax.swing.JButton buttQuit;
    public javax.swing.JButton buttonGoBack;
    public javax.swing.JButton buttonStartOptions;
    public javax.swing.JToggleButton chaosModeButton;
    public javax.swing.JTextField clientAddressTextField;
    public javax.swing.JToggleButton compStartButton;
    public javax.swing.JTextField connectToPortTextField;
    public javax.swing.JRadioButton connectToRadioButton;
    public javax.swing.JToggleButton coopStartButton;
    public javax.swing.JSlider difficultySlider;
    public javax.swing.JPanel explanationPanel;
    public javax.swing.JLabel firstNumLabel;
    public javax.swing.JLabel firstNumLabel1;
    public javax.swing.JPanel firstTimeUsePanel;
    public javax.swing.JToggleButton firstUseQuitButton;
    public javax.swing.JPanel firstplayerPanel;
    public javax.swing.JPanel firstplayersettingsPanel;
    public javax.swing.JLabel gradeSettingLabel;
    public javax.swing.JTextField gradeTextField;
    public javax.swing.JButton helpButton;
    public javax.swing.JButton helpButton1;
    public javax.swing.JLabel highScoreAmount;
    public javax.swing.JButton hintButton;
    public javax.swing.JButton hintButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public java.awt.Label label2;
    public javax.swing.JTextArea leaderBoardTextArea;
    public javax.swing.JTextArea logTextArea;
    public javax.swing.JTextArea logTextArea1;
    public javax.swing.JPanel mainPanel;
    public javax.swing.JLabel nameSettingLabel;
    public javax.swing.JTextField nameTextField;
    public javax.swing.JLabel pointsAmountLabel;
    public javax.swing.JLabel pointsAmountLabel1;
    public javax.swing.JButton quitButton;
    public javax.swing.JButton quitButton1;
    public javax.swing.JButton resetButton;
    public javax.swing.JButton resetButton1;
    public javax.swing.JLabel secondNumLabel;
    public javax.swing.JLabel secondNumLabel1;
    public javax.swing.JTextField serverPortTextField;
    public javax.swing.JLabel serverToConnectLabel;
    public javax.swing.JButton shuffleButton;
    public javax.swing.JButton shuffleButton1;
    public javax.swing.JButton singlePlayerButton;
    public javax.swing.JToggleButton startContinueButton;
    public javax.swing.JPanel startPanel;
    public javax.swing.JToggleButton startSettingsButt;
    private javax.swing.JPanel startSettingsPanel;
    public javax.swing.JToggleButton startTwoPlayerButt;
    public javax.swing.JTextField teacherNameTextField;
    public javax.swing.JLabel teacherSettingLabel;
    public javax.swing.JButton twoPlayerButton;
    public javax.swing.JPanel twoPlayerPanel;
    public javax.swing.JToggleButton twoPlayerQuitButt;
    public javax.swing.JPanel twoPlayerSettingPanel;
    public javax.swing.JPanel twoplayerComporCoOp;
    public javax.swing.JPanel youLosePanel;
    public javax.swing.JToggleButton youLoseQuitButton;
    public javax.swing.JPanel youwinPanel;
    // End of variables declaration//GEN-END:variables
}

